---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- libs/trackball.js
